import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "../components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-full">
          <div className="hidden md:flex w-56 flex-col fixed inset-y-0 z-5 ">
            <Sidebar />
          </div>
          <main className="md:pl-56 h-screen mx-20 flex items-center justify-center">
            {children}
            </main>
        </div>
      </body>
    </html>
  );
}
