import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../styles/globals.css'
import Sidebar from '@/components/sidebar'
import Header from '@/components/header/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Data Collection',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          <div>
            <Sidebar />
          </div>
          <div className="flex-col">
            <div className=''>
              <Header />
            </div>
            <div className='bg-fourth flex-1'>{children}</div>
          </div>
        </div>
      </body>
    </html>
  )
}
