import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../styles/globals.css'
import Sidebar from '@/components/Sidebar'
import Header from '@/components/header/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Data Collection',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex bg-fourth pl-3">
          <Sidebar />
          <div className="flex-1 md:flex h-screen relative">
            <Header />
            <div className='bg-fourth flex-1'>
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  )
}
